### ISSUE TITLE
switch submission type of SynTree/TreeToFormula task from `PropFormula` to `SynTree BinOp Char`?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#32]
I am not fully clear on what is the advantage of one over the other. Would the main difference be in which parser is used for the student input? That is, https://github.com/fmidue/logic-tasks/blob/072bb95f66c50c316a082d9ec17f2615da34a0cb/src/Trees/Parsing.hs#L90 vs. https://github.com/fmidue/logic-tasks/blob/072bb95f66c50c316a082d9ec17f2615da34a0cb/src/Trees/Parsing.hs#L36 Is there an advantage of one parser over the other in terms of student friendliness of error messages or so?

**Comment by patritzenfeld** [comment]
I mainly used this other type because the input for the tasks was not uniform. The tasks for removing redundant brackets used a string input since it isn't a valid syntax tree. For the others, it would be SynTree. 
Also, I thought that the input type "SynTree" would be rather confusing for students.

**Comment by jvoigtlaender** [comment]
Das mit dem den Studierenden angezeigten Typnamen kann man später ja noch mittels eines newtype-Wrappers beheben.

**Comment by jvoigtlaender** [comment]
Just for the record, the `SubTreeSet` task needs to stay as using the `PropFormula` type for inputs, I think (just like the `SimplestFormula` task).
